### ISSUE TITLE
Is posible change size?

### ISSUE THREAD

**Issue by webserveis** [nntuyen/text-decorator#2]
Is posible decore with diferent size Text?

**Comment by jamesnguyenhub** [comment]
Hi @webserveis,

You can do it using `.setRelativeSize`.
```java
String text = "text and the bigger one";

TextDecorator
        .decorate(tvContent, text)
        .setRelativeSize(0.5f, "text")
        .setRelativeSize(1.5f, "the bigger one")
        .build();
```

Result
[![Screenshot2017-01-0122.08.3204713.th.png](https://s1.upanh123.com/2017/01/01/Screenshot2017-01-0122.08.3204713.th.png)](https://upanh123.com/image/oIR7)
